Fixes a bug in dataflow.py that causes stdout, stderr to be None when an error occurs:
```
% gsutil cat gs://ttl-30d-us-central2-0rxn/axlearn/jobs/rpang-ajax-dataflow-20240204-2002/output/rpang-ajax-dataflow-20240204-2002/run.log
...
RuntimeError: Popen command bash -c '...' returned non-zero exit code 1:
stdout=None
stderr=None
```

According to https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate:

> Note that if you want to send data to the process’s stdin, you need to create the Popen object with stdin=PIPE. Similarly, to get anything other than None in the result tuple, you need to give stdout=PIPE and/or stderr=PIPE too.